'use client';
import Layout from '@/components/layout';
import GlobalStyle from '@/styles/global';
import { theme } from '@/styles/theme';
import { usePathname } from 'next/navigation';
import { ReactNode } from 'react';
import { ThemeProvider } from 'styled-components';
import { Roboto } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '400', '500'],
});

export default function RootLayout({ children }: { children: ReactNode }) {
  const publicRoute = ['/', '/login', 'recoverPassword/'];
  const pathname = usePathname();
  console.log(pathname);

  function verifyRouter() {
    const currentRoute = pathname;
    return publicRoute.includes(currentRoute);
  }

  return (
    <html lang="pt-BR" className={roboto.className}>
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <body>
          {verifyRouter() ? <>{children}</> : <Layout>{children}</Layout>}
        </body>
      </ThemeProvider>
    </html>
  );
}
